import Head from "next/head"
import Banner from "../components/Banner"
import ContinueWatching from "../components/ContinueWatching"
import ImageRow from "../components/ImageRow"
import requests from "../utils/requests"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <Banner />

      {/* Continue Watching */}
      <ContinueWatching />

      {/* List */}
      <div className="pt-[50px] pb-[50px] md:pt-[100px] md:pb-[100px]">
        <ImageRow title="My List" fetchUrl={requests.fetchTopRated} />
        <ImageRow title="Popular" fetchUrl={requests.fetchNowPlaying} />
        <ImageRow title="Coming soon" fetchUrl={requests.fetchUpcoming} />
      </div>
    </div>
  )
}
