import Head from "next/head"
import Banner from "../components/Banner"
import ImageRow from "../components/ImageRow"
import requests from "../utils/requests"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <Banner />

      {/* List */}
      <div className="pb-[80px]">
        <ImageRow title="My List" fetchUrl={requests.fetchTopRated} />
        <ImageRow title="Popular" fetchUrl={requests.fetchTrending} />
        <ImageRow title="Coming soon" fetchUrl={requests.fetchUpcoming} />
      </div>
    </div>
  )
}
