import axios from "axios"
import Head from "next/head"
import Image from "next/image"
import Banner from "../components/Banner"
// import { server } from "../utils/requests"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <Banner />
    </div>
  )
}

// export async function getStaticProps() {
//   const res = await axios(
//     `${server}/trending/all/week?api_key=${process.env.API_KEY}&language=en-US`
//   )
//   const movies = res.data

//   return {
//     props: { movies },
//   }
// }
